export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const MARK_ID_AS_ACTIVE = 'MARK_ID_AS_ACTIVE';

export const REQUEST_VIEW = 'REQUEST_VIEW';
export const RECEIVE_VIEW = 'RECEIVE_VIEW';